[project]
authors = ["Guillaume Lemaitre <guillaume@probabl.ai>"]
channels = ["conda-forge"]
description = "Introduction to scikit-learn for the TRACES program"
name = "traces-sklearn"
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.2.4,<5"
jupytext = ">=1.16.4,<2"
notebook = ">=7.2.1,<8"
numpy = ">=2.0.1,<3"
scipy = ">=1.14.0,<2"
scikit-learn = ">=1.5.1,<2"
pandas = ">=2.2.2,<3"
matplotlib = ">=3.9.1,<4"
pyarrow = ">=17.0.0,<18"

[feature.dev.dependencies]
ipykernel = "*"
ipython = "*"

[feature.docs.dependencies]
jupyter-book = "*"
jupyterlite = "*"
jupyter_server = "*"
jupyterlab_server = "*"
jupyterlite-pyodide-kernel = "*"
python-libarchive-c = "*"

[feature.docs.tasks]
convert-to-notebooks = { cmd = "jupytext --to notebook ./content/python_files/*.py && mkdir -p ./content/notebooks && mv ./content/python_files/*.ipynb ./content/notebooks" }
convert-to-executed-notebooks = { cmd = "jupytext --to notebook --execute ./content/python_files/*.py && mkdir -p ./content/notebooks && mv ./content/python_files/*.ipynb ./content/notebooks" }
build-book = { cmd = "jupyter-book build book", depends-on = ["convert-to-notebooks"] }
build-jupyterlite = { cmd = "jupyter lite build --contents content --output-dir dist", cwd = "jupyterlite" }

[environments]
docs = ["docs"]
dev = ["dev", "docs"]
