name: 'test_environments'

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test-conda:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true

      - name: Install dependencies with conda and check sklearn
        shell: bash -el {0}
        run: |
          conda env create -f environment.yml
          conda activate traces-sklearn
          python -c "import sklearn; print(sklearn.__version__)"

  test-pip:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies with pip
        run: pip install -r requirements.txt

      - name: Test sklearn import
        run: python -c "import sklearn; print(sklearn.__version__)"
